In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('elections.csv')

In [3]:
df

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [4]:
df[["Year", "Party"]].groupby("Year").agg(sum)

C:\Users\mujee\AppData\Local\Temp\ipykernel_9424\32577649.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df[["Year", "Party"]].groupby("Year").agg(sum)

                                                  Party
Year
1824         Democratic-RepublicanDemocratic-Republican
1828                      DemocraticNational Republican
1832          DemocraticNational RepublicanAnti-Masonic
1836                                 WhigDemocraticWhig
1840                                     DemocraticWhig
1844                                     WhigDemocratic
1848                            DemocraticFree SoilWhig
1852                            DemocraticFree SoilWhig
1856                       DemocraticRepublicanAmerican
1860  RepublicanConstitutional UnionSouthern Democra...
1864                           National UnionDemocratic
1868                               DemocraticRepublican
1872                       Liberal RepublicanRepublican
1876                               RepublicanDemocratic
1880                      GreenbackRepublicanDemocratic
1884       Anti-MonopolyDemocraticRepublicanProhibition
1888         Union LaborRepublicanProhibitionDemocratic
1892            RepublicanDemocraticPopulistProhibition
1896  National DemocraticProhibitionDemocraticRepubl...
1900                    ProhibitionDemocraticRepublican
1904   DemocraticSocialistProhibitionRepublicanPopulist
1908           SocialistProhibitionDemocraticRepublican
1912  SocialistProhibitionProgressiveRepublicanDemoc...
1916           SocialistRepublicanProhibitionDemocratic
1920  ProhibitionSocialistDemocraticFarmerâ€“LaborRepu...
1924                    RepublicanDemocraticProgressive
1928                      DemocraticRepublicanSocialist
1932             DemocraticRepublicanSocialistCommunist
1936                 RepublicanDemocraticSocialistUnion
1940                      DemocraticSocialistRepublican
1944                               DemocraticRepublican
1948  ProhibitionDemocraticProgressiveSocialistDixie...
1952                    DemocraticRepublicanProgressive
1956                 DemocraticRepublicanStates' Rights
1960                               DemocraticRepublican
1964                               RepublicanDemocratic
1968           American IndependentDemocraticRepublican
1972           DemocraticAmerican IndependentRepublican
1976  IndependentRepublicanDemocraticAmerican Indepe...
1980  CitizensLibertarianDemocraticIndependentRepubl...
1984                    LibertarianRepublicanDemocratic
1988        RepublicanNew AllianceDemocraticLibertarian
1992  LibertarianDemocraticPopulistRepublicanIndepen...
1996  DemocraticRepublicanLibertarianTaxpayersNatura...
2000         DemocraticRepublicanLibertarianReformGreen
2004  GreenRepublicanDemocraticLibertarianConstituti...
2008  DemocraticLibertarianConstitutionGreenRepublic...
2012               DemocraticLibertarianGreenRepublican
2016  ConstitutionRepublicanIndependentLibertarianDe...
2020               DemocraticRepublicanLibertarianGreen

In [5]:
import urllib.request
import os.path
import zipfile
import pandas as pd

data_url = "https://www.ssa.gov/oact/babynames/state/namesbystate.zip"
local_filename = "babynamesbystate.zip"
if not os.path.exists(local_filename): # if the data exists don't download again
    with urllib.request.urlopen(data_url) as resp, open(local_filename, 'wb') as f:
        f.write(resp.read())

zf = zipfile.ZipFile(local_filename, 'r')

ca_name = 'CA.TXT'
field_names = ['State', 'Sex', 'Year', 'Name', 'Count']
with zf.open(ca_name) as fh:
    babynames = pd.read_csv(fh, header=None, names=field_names)

babynames.head(15)

   State Sex  Year       Name  Count
0     CA   F  1910       Mary    295
1     CA   F  1910      Helen    239
2     CA   F  1910    Dorothy    220
3     CA   F  1910   Margaret    163
4     CA   F  1910    Frances    134
5     CA   F  1910       Ruth    128
6     CA   F  1910     Evelyn    126
7     CA   F  1910      Alice    118
8     CA   F  1910   Virginia    101
9     CA   F  1910  Elizabeth     93
10    CA   F  1910   Florence     93
11    CA   F  1910      Marie     90
12    CA   F  1910    Mildred     90
13    CA   F  1910       Rose     74
14    CA   F  1910      Hazel     68

In [6]:
babynames[["Year", "Count"]].groupby("Year").agg(sum)

C:\Users\mujee\AppData\Local\Temp\ipykernel_9424\3257364118.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  babynames[["Year", "Count"]].groupby("Year").agg(sum)

       Count
Year
1910    9163
1911    9983
1912   17946
1913   22094
1914   26926
...      ...
2019  387325
2020  363307
2021  363206
2022  361960
2023  342550

[114 rows x 1 columns]