In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("elections.csv")
df

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [3]:
df.head()

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789

In [5]:
df.tail()

     Year       Candidate        Party  Popular vote Result          %
177  2016      Jill Stein        Green       1457226   loss   1.073699
178  2020    Joseph Biden   Democratic      81268924    win  51.311515
179  2020    Donald Trump   Republican      74216154   loss  46.858542
180  2020    Jo Jorgensen  Libertarian       1865724   loss   1.177979
181  2020  Howard Hawkins        Green        405035   loss   0.255731

In [9]:
df=pd.read_csv('elections.csv' , index_col="Year")
df

              Candidate                  Party  Popular vote Result          %
Year
1824     Andrew Jackson  Democratic-Republican        151271   loss  57.210122
1824  John Quincy Adams  Democratic-Republican        113142    win  42.789878
1828     Andrew Jackson             Democratic        642806    win  56.203927
1828  John Quincy Adams    National Republican        500897   loss  43.796073
1832     Andrew Jackson             Democratic        702735    win  54.574789
...                 ...                    ...           ...    ...        ...
2016         Jill Stein                  Green       1457226   loss   1.073699
2020       Joseph Biden             Democratic      81268924    win  51.311515
2020       Donald Trump             Republican      74216154   loss  46.858542
2020       Jo Jorgensen            Libertarian       1865724   loss   1.177979
2020     Howard Hawkins                  Green        405035   loss   0.255731

[182 rows x 5 columns]

In [10]:
df2=pd.read_csv('duplicate.csv')
df2

,Year,Candidate,Party,Popular vote,Result,%,Unnamed: 6,Result.1
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122,NaN,loss
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878,NaN,win
2,1828,Andrew Jackson,Democratic,642806,win,56.203927,NaN,win
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073,NaN,loss
4,1832,Andrew Jackson,Democratic,702735,win,54.574789,NaN,win
...,...,...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699,NaN,loss
178,2020,Joseph Biden,Democratic,81268924,win,51.311515,NaN,win
179,2020,Donald Trump,Republican,74216154,loss,46.858542,NaN,loss
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979,NaN,loss
181,2020,Howard Hawkins,Green,405035,loss,0.255731,NaN,loss

In [14]:
df.columns

Index(['Candidate', 'Party', 'Popular vote', 'Result', '%'], dtype='object')

In [15]:
df['Party']

Year
1824    Democratic-Republican
1824    Democratic-Republican
1828               Democratic
1828      National Republican
1832               Democratic
                ...
2016                    Green
2020               Democratic
2020               Republican
2020              Libertarian
2020                    Green
Name: Party, Length: 182, dtype: object

In [16]:
df['Result']

Year
1824    loss
1824     win
1828     win
1828    loss
1832     win
        ...
2016    loss
2020     win
2020    loss
2020    loss
2020    loss
Name: Result, Length: 182, dtype: object

In [18]:
df[['Party', 'Result']]

                      Party Result
Year
1824  Democratic-Republican   loss
1824  Democratic-Republican    win
1828             Democratic    win
1828    National Republican   loss
1832             Democratic    win
...                     ...    ...
2016                  Green   loss
2020             Democratic    win
2020             Republican   loss
2020            Libertarian   loss
2020                  Green   loss

[182 rows x 2 columns]

# Series

In [19]:
import pandas as pd

In [22]:
s=pd.Series(['ABCDE', "FGHIJ", "KLMNO", "PQRST", "UVWX"])
s

0    ABCDE
1    FGHIJ
2    KLMNO
3    PQRST
4     UVWX
dtype: object

In [24]:
s=pd.Series(['ABCDE', "FGHIJ", "KLMNO", "PQRST", "UVWX"], index=['10', '20', '30', '40', '50'])
s

10    ABCDE
20    FGHIJ
30    KLMNO
40    PQRST
50     UVWX
dtype: object

In [26]:
s[['20' , '40']]

20    FGHIJ
40    PQRST
dtype: object

# Data Frame using Pandas

In [31]:
pd.DataFrame([1,2,3,4,5], columns= ["col"])

   col
0    1
1    2
2    3
3    4
4    5

In [33]:
pd.DataFrame([["qd", 'dqd', 'qdwq', 'lcdv'], ['vds', 'qwd', 'dfw', 'vows']] , columns=['sad', 'happy', 'no', 'yes'])

   sad happy    no   yes
0   qd   dqd  qdwq  lcdv
1  vds   qwd   dfw  vows

In [38]:
pd.DataFrame([['fas', 'fwas', 'ok', 'vd', 'aa'], ['zz', 'bb', 'ww', 'vv', 'aa'], ['vs', 'vb', 'bb', 'kk', 'bb']], columns= ['A','B', 'C', 'D', "E"])

     A     B   C   D   E
0  fas  fwas  ok  vd  aa
1   zz    bb  ww  vv  aa
2   vs    vb  bb  kk  bb

In [42]:
df=pd.read_csv('elections.csv')
df

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [43]:
df.head()

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789

In [45]:
pd.read_csv('elections.csv', index_col="Result")

,Year,Candidate,Party,Popular vote,%
Result,,,,,
loss,1824,Andrew Jackson,Democratic-Republican,151271,57.210122
win,1824,John Quincy Adams,Democratic-Republican,113142,42.789878
win,1828,Andrew Jackson,Democratic,642806,56.203927
loss,1828,John Quincy Adams,National Republican,500897,43.796073
win,1832,Andrew Jackson,Democratic,702735,54.574789
...,...,...,...,...,...
loss,2016,Jill Stein,Green,1457226,1.073699
win,2020,Joseph Biden,Democratic,81268924,51.311515
loss,2020,Donald Trump,Republican,74216154,46.858542
loss,2020,Jo Jorgensen,Libertarian,1865724,1.177979
loss,2020,Howard Hawkins,Green,405035,0.255731